// Code generated by qtc from "basepage.gtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a base page template. All the other template pages implement this interface.
//

//line basepage.gtpl:3
package templates

//line basepage.gtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line basepage.gtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line basepage.gtpl:4
type Page interface {
//line basepage.gtpl:4
	Title() string
//line basepage.gtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line basepage.gtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line basepage.gtpl:4
	Body() string
//line basepage.gtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line basepage.gtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line basepage.gtpl:4
}

// Page prints a page implementing Page interface.

//line basepage.gtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line basepage.gtpl:12
	qw422016.N().S(`
<html>
	<head>
		<title>`)
//line basepage.gtpl:15
	p.StreamTitle(qw422016)
//line basepage.gtpl:15
	qw422016.N().S(`</title>
	</head>
	<body>
		<div>
			<a href="/">return to main page</a>
		</div>
		`)
//line basepage.gtpl:21
	p.StreamBody(qw422016)
//line basepage.gtpl:21
	qw422016.N().S(`
	</body>
</html>
`)
//line basepage.gtpl:24
}

//line basepage.gtpl:24
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line basepage.gtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line basepage.gtpl:24
	StreamPageTemplate(qw422016, p)
//line basepage.gtpl:24
	qt422016.ReleaseWriter(qw422016)
//line basepage.gtpl:24
}

//line basepage.gtpl:24
func PageTemplate(p Page) string {
//line basepage.gtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line basepage.gtpl:24
	WritePageTemplate(qb422016, p)
//line basepage.gtpl:24
	qs422016 := string(qb422016.B)
//line basepage.gtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line basepage.gtpl:24
	return qs422016
//line basepage.gtpl:24
}

// Base page implementation. Other pages may inherit from it if they need
// overriding only certain Page methods

//line basepage.gtpl:29
type BasePage struct{}

//line basepage.gtpl:30
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line basepage.gtpl:30
	qw422016.N().S(`This is a base title`)
//line basepage.gtpl:30
}

//line basepage.gtpl:30
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line basepage.gtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line basepage.gtpl:30
	p.StreamTitle(qw422016)
//line basepage.gtpl:30
	qt422016.ReleaseWriter(qw422016)
//line basepage.gtpl:30
}

//line basepage.gtpl:30
func (p *BasePage) Title() string {
//line basepage.gtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line basepage.gtpl:30
	p.WriteTitle(qb422016)
//line basepage.gtpl:30
	qs422016 := string(qb422016.B)
//line basepage.gtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line basepage.gtpl:30
	return qs422016
//line basepage.gtpl:30
}

//line basepage.gtpl:31
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line basepage.gtpl:31
	qw422016.N().S(`This is a base body`)
//line basepage.gtpl:31
}

//line basepage.gtpl:31
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line basepage.gtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line basepage.gtpl:31
	p.StreamBody(qw422016)
//line basepage.gtpl:31
	qt422016.ReleaseWriter(qw422016)
//line basepage.gtpl:31
}

//line basepage.gtpl:31
func (p *BasePage) Body() string {
//line basepage.gtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line basepage.gtpl:31
	p.WriteBody(qb422016)
//line basepage.gtpl:31
	qs422016 := string(qb422016.B)
//line basepage.gtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line basepage.gtpl:31
	return qs422016
//line basepage.gtpl:31
}
