// Code generated by qtc from "errorpage.gtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Error page template. Implements BasePage methods.
//

//line errorpage.gtpl:3
package templates

//line errorpage.gtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line errorpage.gtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line errorpage.gtpl:4
type ErrorPage struct {
	// inherit from base page, so its' title is used in error page.
	BasePage

	// error path
	Path []byte
}

//line errorpage.gtpl:14
func (p *ErrorPage) StreamBody(qw422016 *qt422016.Writer) {
//line errorpage.gtpl:14
	qw422016.N().S(`
	<h1>Error page</h1>
	</div>
		Unsupported path <b>`)
//line errorpage.gtpl:17
	qw422016.E().Z(p.Path)
//line errorpage.gtpl:17
	qw422016.N().S(`</b>.
	</div>
	Base page body: `)
//line errorpage.gtpl:19
	p.BasePage.StreamBody(qw422016)
//line errorpage.gtpl:19
	qw422016.N().S(`
`)
//line errorpage.gtpl:20
}

//line errorpage.gtpl:20
func (p *ErrorPage) WriteBody(qq422016 qtio422016.Writer) {
//line errorpage.gtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line errorpage.gtpl:20
	p.StreamBody(qw422016)
//line errorpage.gtpl:20
	qt422016.ReleaseWriter(qw422016)
//line errorpage.gtpl:20
}

//line errorpage.gtpl:20
func (p *ErrorPage) Body() string {
//line errorpage.gtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line errorpage.gtpl:20
	p.WriteBody(qb422016)
//line errorpage.gtpl:20
	qs422016 := string(qb422016.B)
//line errorpage.gtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line errorpage.gtpl:20
	return qs422016
//line errorpage.gtpl:20
}
