// Code generated by qtc from "mainpage.gtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line mainpage.gtpl:3
package templates

//line mainpage.gtpl:3
import "github.com/valyala/fasthttp"

//line mainpage.gtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line mainpage.gtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line mainpage.gtpl:6
type MainPage struct {
	CTX *fasthttp.RequestCtx
}

//line mainpage.gtpl:12
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line mainpage.gtpl:12
	qw422016.N().S(`
	This is the main page
`)
//line mainpage.gtpl:14
}

//line mainpage.gtpl:14
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line mainpage.gtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mainpage.gtpl:14
	p.StreamTitle(qw422016)
//line mainpage.gtpl:14
	qt422016.ReleaseWriter(qw422016)
//line mainpage.gtpl:14
}

//line mainpage.gtpl:14
func (p *MainPage) Title() string {
//line mainpage.gtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line mainpage.gtpl:14
	p.WriteTitle(qb422016)
//line mainpage.gtpl:14
	qs422016 := string(qb422016.B)
//line mainpage.gtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line mainpage.gtpl:14
	return qs422016
//line mainpage.gtpl:14
}

//line mainpage.gtpl:17
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line mainpage.gtpl:17
	qw422016.N().S(`
	<h1>Main page</h1>
	<div>
		Click links below:
		<ul>
			<li><a href="/table?rowsCount=42">Table page</a></li>
			<li><a href="/unknown-page">Error page</a></li>
		</ul>
	</div>
	<div>
		Some info about you:<br/>
		IP: <b>`)
//line mainpage.gtpl:28
	qw422016.E().S(p.CTX.RemoteIP().String())
//line mainpage.gtpl:28
	qw422016.N().S(`</b><br/>
		User-Agent: <b>`)
//line mainpage.gtpl:29
	qw422016.E().Z(p.CTX.UserAgent())
//line mainpage.gtpl:29
	qw422016.N().S(`</b><br/>
	</div>
`)
//line mainpage.gtpl:31
}

//line mainpage.gtpl:31
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line mainpage.gtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mainpage.gtpl:31
	p.StreamBody(qw422016)
//line mainpage.gtpl:31
	qt422016.ReleaseWriter(qw422016)
//line mainpage.gtpl:31
}

//line mainpage.gtpl:31
func (p *MainPage) Body() string {
//line mainpage.gtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line mainpage.gtpl:31
	p.WriteBody(qb422016)
//line mainpage.gtpl:31
	qs422016 := string(qb422016.B)
//line mainpage.gtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line mainpage.gtpl:31
	return qs422016
//line mainpage.gtpl:31
}
