// Code generated by qtc from "tablepage.gtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Table page template. Implements BasePage methods.
//

//line tablepage.gtpl:3
package templates

//line tablepage.gtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line tablepage.gtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line tablepage.gtpl:4
type TablePage struct {
	Rows []string
}

//line tablepage.gtpl:10
func (p *TablePage) StreamTitle(qw422016 *qt422016.Writer) {
//line tablepage.gtpl:10
	qw422016.N().S(`
	This is table page
`)
//line tablepage.gtpl:12
}

//line tablepage.gtpl:12
func (p *TablePage) WriteTitle(qq422016 qtio422016.Writer) {
//line tablepage.gtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tablepage.gtpl:12
	p.StreamTitle(qw422016)
//line tablepage.gtpl:12
	qt422016.ReleaseWriter(qw422016)
//line tablepage.gtpl:12
}

//line tablepage.gtpl:12
func (p *TablePage) Title() string {
//line tablepage.gtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line tablepage.gtpl:12
	p.WriteTitle(qb422016)
//line tablepage.gtpl:12
	qs422016 := string(qb422016.B)
//line tablepage.gtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line tablepage.gtpl:12
	return qs422016
//line tablepage.gtpl:12
}

//line tablepage.gtpl:15
func (p *TablePage) StreamBody(qw422016 *qt422016.Writer) {
//line tablepage.gtpl:15
	qw422016.N().S(`
	<h1>Table page</h1>

	`)
//line tablepage.gtpl:18
	p.streamform(qw422016)
//line tablepage.gtpl:18
	qw422016.N().S(`

	`)
//line tablepage.gtpl:20
	if len(p.Rows) == 0 {
//line tablepage.gtpl:20
		qw422016.N().S(`
		No rows. Click <a href="/table?rowsCount=5">here</a>.
	`)
//line tablepage.gtpl:22
	} else {
//line tablepage.gtpl:22
		qw422016.N().S(`
		<table>
			`)
//line tablepage.gtpl:24
		streamemitRows(qw422016, p.Rows)
//line tablepage.gtpl:24
		qw422016.N().S(`
		</table>
	`)
//line tablepage.gtpl:26
	}
//line tablepage.gtpl:26
	qw422016.N().S(`
`)
//line tablepage.gtpl:27
}

//line tablepage.gtpl:27
func (p *TablePage) WriteBody(qq422016 qtio422016.Writer) {
//line tablepage.gtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tablepage.gtpl:27
	p.StreamBody(qw422016)
//line tablepage.gtpl:27
	qt422016.ReleaseWriter(qw422016)
//line tablepage.gtpl:27
}

//line tablepage.gtpl:27
func (p *TablePage) Body() string {
//line tablepage.gtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line tablepage.gtpl:27
	p.WriteBody(qb422016)
//line tablepage.gtpl:27
	qs422016 := string(qb422016.B)
//line tablepage.gtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line tablepage.gtpl:27
	return qs422016
//line tablepage.gtpl:27
}

//line tablepage.gtpl:29
func streamemitRows(qw422016 *qt422016.Writer, rows []string) {
//line tablepage.gtpl:29
	qw422016.N().S(`
	<tr>
		<th>#</th>
		<th>value</th>
	</tr>

	`)
//line tablepage.gtpl:35
	for n, r := range rows {
//line tablepage.gtpl:35
		qw422016.N().S(`
		`)
//line tablepage.gtpl:36
		if r == "bingo" {
//line tablepage.gtpl:36
			qw422016.N().S(`
			<tr><td colspan="2"><h1>BINGO!</h1></td></tr>
			`)
//line tablepage.gtpl:38
			return
//line tablepage.gtpl:39
		} else if n == 42 {
//line tablepage.gtpl:39
			qw422016.N().S(`
			<tr><td colspan="2">42 rows already generated</td></tr>
			`)
//line tablepage.gtpl:41
			break
//line tablepage.gtpl:42
		}
//line tablepage.gtpl:42
		qw422016.N().S(`

		<tr style="background: `)
//line tablepage.gtpl:44
		if n&1 == 1 {
//line tablepage.gtpl:44
			qw422016.N().S(`white`)
//line tablepage.gtpl:44
		} else {
//line tablepage.gtpl:44
			qw422016.N().S(`#ddd`)
//line tablepage.gtpl:44
		}
//line tablepage.gtpl:44
		qw422016.N().S(`">
			<td>`)
//line tablepage.gtpl:45
		qw422016.N().D(n + 1)
//line tablepage.gtpl:45
		qw422016.N().S(`</td>
			<td>`)
//line tablepage.gtpl:46
		qw422016.E().S(r)
//line tablepage.gtpl:46
		qw422016.N().S(`</td>
		</tr>
	`)
//line tablepage.gtpl:48
	}
//line tablepage.gtpl:48
	qw422016.N().S(`

	<tr><td colspan="2">No bingo found</td></tr>
`)
//line tablepage.gtpl:51
}

//line tablepage.gtpl:51
func writeemitRows(qq422016 qtio422016.Writer, rows []string) {
//line tablepage.gtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tablepage.gtpl:51
	streamemitRows(qw422016, rows)
//line tablepage.gtpl:51
	qt422016.ReleaseWriter(qw422016)
//line tablepage.gtpl:51
}

//line tablepage.gtpl:51
func emitRows(rows []string) string {
//line tablepage.gtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line tablepage.gtpl:51
	writeemitRows(qb422016, rows)
//line tablepage.gtpl:51
	qs422016 := string(qb422016.B)
//line tablepage.gtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line tablepage.gtpl:51
	return qs422016
//line tablepage.gtpl:51
}

//line tablepage.gtpl:53
func (p *TablePage) streamform(qw422016 *qt422016.Writer) {
//line tablepage.gtpl:53
	qw422016.N().S(`
	<form>
		Rows: <input type="text" name="rowsCount" value="`)
//line tablepage.gtpl:55
	qw422016.N().D(len(p.Rows))
//line tablepage.gtpl:55
	qw422016.N().S(`"/><br/>
		<input type="submit" value="Generate!"/>
	</form>
`)
//line tablepage.gtpl:58
}

//line tablepage.gtpl:58
func (p *TablePage) writeform(qq422016 qtio422016.Writer) {
//line tablepage.gtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tablepage.gtpl:58
	p.streamform(qw422016)
//line tablepage.gtpl:58
	qt422016.ReleaseWriter(qw422016)
//line tablepage.gtpl:58
}

//line tablepage.gtpl:58
func (p *TablePage) form() string {
//line tablepage.gtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
//line tablepage.gtpl:58
	p.writeform(qb422016)
//line tablepage.gtpl:58
	qs422016 := string(qb422016.B)
//line tablepage.gtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
//line tablepage.gtpl:58
	return qs422016
//line tablepage.gtpl:58
}
